version: "3"
services:

  wikidb:
    image: postgres:14.4-alpine3.16
    environment:
      POSTGRES_DB: wikijs
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: always
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - wikijs

  wiki:
    image: requarks/wiki:2
    depends_on:
      - wikidb
    environment:
      DB_TYPE: postgres
      DB_HOST: wikidb
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wikijs
    restart: always
    ports:
      - "7777:3000"
    networks:
      - wikijs
networks:
  wikijs:
    external: false
